### ISSUE TITLE
begin / exception / end not properly indented

### ISSUE THREAD

**Issue by hrbigelow** [lifepillar/pgsql.vim#12] opened 2019-07-27 16:13 UTC
Hi,

One other issue - could the default indentation be something like:
```
begin
    statement
    statement
exception
    when something
    when something
end
```
currently, the 'exception' keyword is indented as if it were another statement.

Thanks!

**Comment by lifepillar** [comment] 2019-07-27 17:14
Sure, I’ll do it. Be patient!

**Comment by hrbigelow** [comment] 2019-07-27 19:44
Great!  Looking forward to it.

Thanks again for the good work.

Best,

Henry

**Comment by lifepillar** [comment] 2019-07-30 09:48
This should be fixed in the current master. Please reopen if that is not the case.

**Comment by hrbigelow** [comment] 2019-08-02 15:54
Hmm, doesn't seem to be fixed.
```
henry@mac:~/.vim/pack/bundle/start/pgsql$ git log -1
commit 80cedd45736bb79e69a99e275ce62aec264a8c35 (HEAD -> master, origin/master, origin/HEAD)
Author: Lifepillar <lifepillar@lifepillar.me>
Date:   Tue Jul 30 12:54:48 2019 +0300

    Update the README.
```

in vim:
set filetype=pgsql
gg=G
I see the message "17 lines indented"
but I see:

```
create or replace function func(
    _id in integer,
)
returns integer 
language plpgsql as
$$
declare
_i integer;
begin
    if _id != 1 then
        return 2; 
    end if;
    return 3;
    exception when others then
        return 5;
end
$$;
```

**Comment by lifepillar** [comment] 2019-08-03 15:57
Mhm, thanks for reporting. I’ll look into it.

**Comment by lifepillar** [comment] 2019-08-03 20:01
I cannot reproduce it. Please make sure that the the correct ftplugin is loaded (e.g., check the output of `:scriptnames`, and possibly the value of `runtimepath` ). In particular, make sure that `~/.vim/pack/bundle/start/pgsql/indent/pgsql.vim` is loaded and that no other indentation file is loaded after that. I strongly suspect that you are using Vim's SQL plugin instead of `pgsql.vim`.

**Comment by lifepillar** [comment] 2019-08-03 20:16
Ok, I was able to reproduce in `vim --clean` with the following steps. In a new buffer, paste the code above, then:

```vim
:set rtp+=~/.vim/pack/bundle/start/pgsql
:set ft=sql
:SQLSetType pgsql
gg=G
```

In this case, `:scriptnames` shows that both `indent/sql.vim` and `indent/sqlanywhere.vim` are loaded before `indent/pgsql.vim`.  If I do this instead:

```vim
:set rtp+=~/.vim/pack/bundle/start/pgsql
:let g:sql_type_default = 'pgsql'
:set ft=sql
gg=G
```

then the code is indented correctly. In this case, `:scriptnames`  shows that only `indent/sql.vim` and `indent/pgsql.vim` have been loaded.

I need to investigate why the two sequences of commands do not give the same result and, in particular, why `indent/sqlanywhere.vim` seems to affect the behaviour of my plugin.

**Comment by lifepillar** [comment] 2019-08-03 20:26
>why `indent/sqlanywhere.vim` seems to affect the behaviour of my plugin.

Ah, right, that's obvious: `sqlanywhere.vim` defines `b:did_indent` and `indent/pgsql.vim` is not loaded if `b:did_indent` is defined.

According to `:help SQLSetType`, you need to execute the command without parameters to reset the indent and syntax scripts back to their defaults. So, this should work:

```vim
:set rtp+=~/.vim/pack/bundle/start/pgsql
:set ft=sql
:SQLSetType
:SQLSetType pgsql.vim
gg=G
```

except that it doesn't, because it doesn't unlet `b:did_indent`. I think that this is a bug in Vim SQL scripts.

Anyway, does this information help you fix your issue?

**Comment by hrbigelow** [comment] 2019-08-03 20:39
Nice work!  So, I can confirm that if I do the following:

1. launch vim with no arguments
2. paste in the `create or replace function func...` code block
3. execute one of the three command sequences as you've outlined above

...that the only command sequence that produces the proper indentation is:

```
:set rtp+=~/.vim/pack/bundle/start/pgsql
:let g:sql_type_default = 'pgsql'
:set ft=sql
gg=G
```

The other two don't produce the proper indentation.  Also, the successful command block (pasted above this sentence) does not work in an already launched vim instance that has a longer list of :scriptnames.  In that already-launched instance, the history was that I did:

`:set filetype=pgsql`

In any case, yes, this fixes the issue!  I can just relaunch and execute that above block when I need to.  (And, in fact, I don't need the first line, `:set rtp+=~/.vim/pack/bundle/start/pgsql`)

Thanks again for figuring this out, nice work!

**Comment by lifepillar** [comment] 2019-08-03 20:44
Good that you figured it out!

Anyway, there may be something to be done to improve the behaviour under all circumstances, so I am reopening this as a reminder.

**Comment by hrbigelow** [comment] 2019-08-03 21:03
Great, thanks again for your good work.  Look forward to it being even more streamlined, but I can use it with that command sequence for now.

**Comment by lifepillar** [comment] 2019-08-03 21:31
Ok, I have found the culprit (not a Vim bug!) and fixed it in the current master. Now it should behave correctly under all circumstances. Feel free to reopen if that is not the case.

**Closed by lifepillar** 2019-08-03 21:31 UTC
